[project]
name = "zero2prod"
revision = "1.0"

[profiles.default]
DIGITALOCEAN_ACCESS_TOKEN = { description = "DigitalOcean API token for doctl", required = false }
POSTMARK_API_TOKEN = { description = "Postmark API token for sending emails", required = false }
